-- Spec 013 / CodeRabbit round-2 — `snapshots.userId` index.
--
-- !!! THIS FILE IS NOT PICKED UP BY drizzle-kit !!!
-- !!! DO NOT PUT IT IN drizzle/meta/_journal.json !!!
-- !!! DO NOT RUN IT VIA `pnpm run db:push` !!!
--
-- The per-user query used by `scripts/enumerate-objectives.ts` (the
-- SC-011 objective-inventory maintenance CLI) is
-- `where(eq(snapshots.userId, uid))`. Without an index, the column
-- (`varchar(36)`) is read by table scan; with the index, MySQL/TiDB
-- uses an index lookup. The index is also available to any future
-- per-user lookup the engine might add.
--
-- WHY THIS FILE IS MANUAL:
--
-- The schema in `drizzle/schema.ts` intentionally OMITS the index
-- declaration. drizzle-kit regenerates migrations from the schema; if
-- the index were declared there, drizzle-kit would emit a migration on
-- the next `pnpm run db:push` run, and the production deploy path
-- (which goes through the existing TiDB-aware applier for non-trivial
-- changes) would not see this file. The convention matches the
-- `0010_settings_unique_index.sql` precedent set by Spec 011.
--
-- HOW TO APPLY THIS FILE:
--
--   scripts/apply-migrations.mjs is hard-coded to migrations 0005 and
--   0006 (a special-case early-TiDB bootstrapping path) — it does NOT
--   accept arbitrary files. Use a direct mysql2 / mysql command instead:
--
--     npx tsx -e 'import {readFileSync} from "fs"; import {createConnection} from "mysql2/promise"; import {URL} from "url"; (async()=>{const u=new URL(process.env.DATABASE_URL);const c=await createConnection({host:u.hostname,port:u.port?Number(u.port):undefined,user:u.username,password:u.password,database:u.pathname.slice(1),ssl:{rejectUnauthorized:false},multipleStatements:true});try{await c.query(readFileSync("drizzle/0011_snapshots_user_index.sql","utf-8"));console.log("OK");}finally{await c.end();}})()'
--
--   Or the equivalent single-statement invocation (omit `-p<password>` so
--   the password is read from a prompt or `MYSQL_PWD` env var instead of
--   showing up in `ps` / shell history):
--
--     mysql -h<host>${u.port?` -P${u.port}`:""} -u<user> -p <database> < drizzle/0011_snapshots_user_index.sql
--
-- IDEMPOTENCY: the statement is NOT idempotent — `CREATE INDEX` fails
-- with `ER_DUP_KEYNAME` (1061) on a second run. Either guard the
-- command (`SELECT ... FROM information_schema.statistics WHERE ...`)
-- or accept the failure and rely on the row-count check to confirm
-- the index exists.
--
-- SAFE TO APPLY ANYTIME: `CREATE INDEX` is online for InnoDB / TiDB
-- and requires no exclusive lock. Existing rows are unaffected.

CREATE INDEX `idx_snapshots_userId` ON `snapshots` (`userId`);